import fs from "node:fs";
import path from "node:path";

const source = process.argv[2];
if (!source) throw new Error("用法：node scripts/build-cn-data.mjs <exercises.json>");
const records = JSON.parse(fs.readFileSync(source, "utf8"));

const categories = { back:"背部", cardio:"有氧", chest:"胸部", "lower arms":"前臂", "lower legs":"小腿", neck:"颈部", shoulders:"肩部", "upper arms":"上臂", "upper legs":"大腿", waist:"腰腹" };
const equipment = { assisted:"辅助器械", band:"弹力带", barbell:"杠铃", "body weight":"自重", "bosu ball":"波速球", cable:"绳索器械", dumbbell:"哑铃", "elliptical machine":"椭圆机", "ez barbell":"曲杆杠铃", hammer:"锤式器械", kettlebell:"壶铃", "leverage machine":"固定器械", "medicine ball":"药球", "olympic barbell":"奥林匹克杠铃", "resistance band":"阻力带", roller:"泡沫轴", rope:"训练绳", "skierg machine":"滑雪机", "sled machine":"雪橇机", "smith machine":"史密斯机", "stability ball":"健身球", "stationary bike":"动感单车", "stepmill machine":"登阶机", tire:"轮胎", "trap bar":"六角杠铃", "upper body ergometer":"上肢功率车", weighted:"负重", "wheel roller":"健腹轮" };
const muscles = {
  abductors:"外展肌", abs:"腹肌", abdominals:"腹肌", adductors:"内收肌", "ankle stabilizers":"踝关节稳定肌", ankles:"脚踝", biceps:"肱二头肌", calves:"小腿肌", "cardiovascular system":"心肺系统", chest:"胸肌", core:"核心肌群", deltoids:"三角肌", delts:"三角肌", forearms:"前臂肌", glutes:"臀肌", hamstrings:"腘绳肌", hands:"手部肌群", "hip flexors":"髋屈肌", lats:"背阔肌", "latissimus dorsi":"背阔肌", "levator scapulae":"肩胛提肌", "lower back":"下背部", obliques:"腹斜肌", pectorals:"胸大肌", quads:"股四头肌", quadriceps:"股四头肌", rhomboids:"菱形肌", "rotator cuff":"肩袖肌群", "serratus anterior":"前锯肌", shoulders:"肩部肌群", soleus:"比目鱼肌", spine:"脊柱肌群", trapezius:"斜方肌", traps:"斜方肌", triceps:"肱三头肌", "upper back":"上背部", "wrist extensors":"腕伸肌", "wrist flexors":"腕屈肌", wrists:"手腕肌群"
};

const phrases = {
  "barbell bench press":"杠铃卧推", "barbell full squat":"杠铃深蹲", "pull-up":"引体向上", "push-up":"俯卧撑", "bodyweight squat":"自重深蹲", "romanian deadlift":"罗马尼亚硬拉", "stiff leg deadlift":"直腿硬拉", "sumo deadlift":"相扑硬拉", "deadlift":"硬拉", "lat pulldown":"高位下拉", "front raise":"前平举", "lateral raise":"侧平举", "rear delt":"后三角肌", "biceps curl":"肱二头弯举", "bicep curl":"肱二头弯举", "triceps extension":"肱三头伸展", "tricep extension":"肱三头伸展", "preacher curl":"牧师凳弯举", "hammer curl":"锤式弯举", "concentration curl":"集中弯举", "wrist curl":"腕弯举", "calf raise":"提踵", "leg press":"腿举", "leg extension":"腿屈伸", "leg curl":"腿弯举", "hip thrust":"臀推", "glute bridge":"臀桥", "shoulder press":"肩推", "military press":"军式推举", "chest press":"胸推", "chest fly":"夹胸", "reverse fly":"反向飞鸟", "upright row":"直立划船", "bent over row":"俯身划船", "seated row":"坐姿划船", "one arm row":"单臂划船", "pullover":"上拉", "shrug":"耸肩", "good morning":"早安式", "russian twist":"俄罗斯转体", "sit-up":"仰卧起坐", "crunch":"卷腹", "plank":"平板支撑", "mountain climber":"登山跑", "jumping jack":"开合跳", "burpee":"波比跳", "lunge":"弓步", "split squat":"分腿蹲", "hack squat":"哈克深蹲", "goblet squat":"高脚杯深蹲", "box squat":"箱式深蹲", "sissy squat":"西斯深蹲", "overhead squat":"过顶深蹲", "front squat":"前蹲", "clean and jerk":"挺举", "clean":"翻举", "snatch":"抓举", "kettlebell swing":"壶铃摆动", "face pull":"面拉", "pushdown":"下压", "kickback":"后踢", "chin-up":"反握引体", "dip":"双杠臂屈伸", "hyperextension":"背部伸展", "back extension":"背部伸展", "hip abduction":"髋外展", "hip adduction":"髋内收", "neck stretch":"颈部拉伸", "hamstring stretch":"腘绳肌拉伸", "chest stretch":"胸部拉伸", "shoulder stretch":"肩部拉伸", "quadriceps stretch":"股四头肌拉伸", "calf stretch":"小腿拉伸", "arm circles":"手臂画圈", "jump rope":"跳绳", "stationary bike":"动感单车", "elliptical machine":"椭圆机"
};
const words = {
  dumbbell:"哑铃", barbell:"杠铃", cable:"绳索", band:"弹力带", kettlebell:"壶铃", smith:"史密斯机", lever:"固定器械", weighted:"负重", assisted:"辅助", bodyweight:"自重", medicine:"药球", stability:"健身球", bosu:"波速球", rope:"训练绳", machine:"器械", roller:"滚轮", sled:"雪橇", wheel:"健腹轮", ez:"曲杆", olympic:"奥林匹克",
  seated:"坐姿", standing:"站姿", lying:"卧姿", incline:"上斜", decline:"下斜", prone:"俯卧", supine:"仰卧", kneeling:"跪姿", hanging:"悬垂", bent:"俯身", upright:"直立", overhead:"过顶", front:"前", rear:"后", side:"侧向", lateral:"侧向", reverse:"反向", close:"窄距", wide:"宽距", narrow:"窄距", neutral:"中立握", underhand:"反握", parallel:"平行握", single:"单侧", one:"单", two:"双", alternate:"交替", alternating:"交替", straight:"直臂", full:"全幅", half:"半程", inner:"内侧", lower:"下部", upper:"上部", high:"高位", low:"低位", vertical:"垂直", horizontal:"水平", circular:"环绕", rotational:"旋转",
  arm:"手臂", arms:"手臂", leg:"腿", legs:"腿", chest:"胸部", shoulder:"肩部", shoulders:"肩部", back:"背部", hip:"髋部", glute:"臀肌", hamstring:"腘绳肌", triceps:"肱三头肌", tricep:"肱三头肌", biceps:"肱二头肌", bicep:"肱二头肌", calf:"小腿", calves:"小腿", wrist:"手腕", neck:"颈部", knee:"膝部", knees:"膝部", ankle:"脚踝", abs:"腹肌", abdominal:"腹部", oblique:"腹斜肌", lat:"背阔肌", delt:"三角肌", scapula:"肩胛", pelvic:"骨盆", forearm:"前臂", quads:"股四头肌", piriformis:"梨状肌", muscle:"肌肉", hands:"双手", hand:"手", head:"头部", toe:"脚尖",
  curl:"弯举", curls:"弯举", press:"推举", raise:"抬举", raises:"抬举", row:"划船", extension:"伸展", flexion:"屈曲", squat:"深蹲", fly:"飞鸟", pull:"拉", push:"推", pulldown:"下拉", crunch:"卷腹", stretch:"拉伸", exercise:"训练", bend:"侧屈", twist:"转体", rotation:"旋转", bridge:"臀桥", jump:"跳跃", jumps:"跳跃", run:"跑", lift:"提拉", throw:"投掷", walk:"行走", walking:"行走", swing:"摆动", hang:"悬挂", hanging:"悬垂", touch:"触碰", reach:"伸展触碰", kick:"踢腿", drag:"拖拉", crawl:"爬行", tap:"点触", thrust:"推髋", adduction:"内收", abduction:"外展", circles:"画圈", motion:"运动", balance:"平衡", support:"支撑", dip:"臂屈伸", dips:"臂屈伸", down:"下压", up:"上举", pose:"姿势", hold:"保持", step:"踏步", walk:"行走", jerk:"挺举", clean:"翻举", snatch:"抓举", jack:"开合跳", climber:"登山跑", plank:"平板支撑", burpee:"波比跳", lunge:"弓步", deadlift:"硬拉", squat:"深蹲", shrug:"耸肩", pullover:"上拉", pushdown:"下压", kickback:"后踢", rollerout:"滚轮前伸", hyperextension:"背部伸展", windmill:"风车式", thruster:"深蹲推举", planche:"俄式挺身", pike:"屈体", tuck:"收膝", tilt:"倾斜", flip:"翻转", drop:"下落", slingers:"甩动",
  grip:"握", bar:"杆", bench:"训练凳", ball:"球", floor:"地面", wall:"墙面", towel:"毛巾", chair:"椅子", box:"箱式", attachment:"附件", trainer:"训练器", blaster:"训练器", cage:"深蹲架", fixed:"固定", suspended:"悬吊", resistance:"阻力", body:"身体", bike:"单车", tire:"轮胎", pulley:"滑轮", hammer:"锤式", spider:"蜘蛛式", archer:"射手式", donkey:"驴式", frog:"蛙式", cuban:"古巴式", arnold:"阿诺德", zottman:"佐特曼", zercher:"泽奇式", bradford:"布拉德福德式", russian:"俄罗斯式", french:"法式", romanian:"罗马尼亚式", sumo:"相扑式", military:"军式", pallof:"帕洛夫", skull:"仰卧臂屈伸", rocky:"洛奇式", pov:"视角示范",
  with:"", on:"", over:"", to:"", and:"", the:"", of:"", from:"", in:"", a:"", against:"", through:"", between:"", self:"自助", male:"男士", female:"女士", palms:"掌心", palm:"掌心", behind:"颈后", around:"环绕", forward:"向前", extended:"伸直", raised:"抬高", twisting:"旋转", twisted:"扭转", squatting:"深蹲", stance:"站距", range:"幅度", internal:"内旋", external:"外旋", flexor:"屈肌", inverse:"反向", revers:"反向", sitted:"坐姿", rocking:"摇摆", plyo:"增强式", sling:"悬吊"
};

Object.assign(words, {
  air:"空中", all:"全", fours:"四点支撑", squad:"组合", heel:"脚跟", touchers:"触碰", apart:"分开", sit:"起坐", ups:"上举", elbow:"肘部", inverted:"倒立", double:"双侧", chin:"下巴", bars:"双杠", flat:"平板", bottoms:"底朝上", cross:"交叉", crossovers:"交叉拉", crossover:"交叉", stork:"鹳式", finger:"手指", iron:"铁十字", face:"面部", deltoid:"三角肌", pronation:"旋前", supination:"旋后", world:"环绕世界", off:"离地", hug:"环抱", tennis:"网球", kicks:"踢腿", maltese:"马耳他式", march:"原地踏步", hack:"哈克式", clasped:"交握", handstand:"倒立", inchworm:"毛毛虫式", isometric:"等长", squeeze:"夹紧", pass:"传递", pistol:"手枪式", landmine:"地雷管", gripless:"免握", point:"点位", response:"反应", slam:"砸球", modified:"改良式", posterior:"后侧", potty:"便盆式", power:"力量式", hyper:"超伸展", depresor:"下压肌", retractor:"后缩肌", ski:"滑雪式", spine:"脊柱", squats:"深蹲", straddle:"跨坐", three:"三点", glutes:"臀肌", gluteus:"臀肌", rectus:"直肌", femoris:"股肌", pectoralis:"胸肌", major:"大肌", adductor:"内收肌", astride:"跨骑", forth:"往复", pec:"胸肌", backward:"向后", board:"板式", bicycle:"自行车式", knife:"刀式", under:"下方", both:"双侧", guillotine:"断头台式", jefferson:"杰斐逊式", lifting:"提拉", crusher:"屈伸", pendlay:"潘德雷式", pin:"插销式", presses:"推举", rack:"架上", skullcrusher:"仰卧臂屈伸", skier:"滑雪式", speed:"快速", ab:"腹部", stiff:"僵直", basic:"基础", battling:"战绳", ropes:"训练绳", bear:"熊爬", stabilization:"稳定", butt:"臀部", butterfly:"蝴蝶式", yoga:"瑜伽", concentration:"集中式", variation:"变式", judo:"柔道式", middle:"中部", pro:"专业式", stirrups:"脚蹬", drive:"推蹬", sz:"SZ式", elevated:"垫高", twists:"转体", thibaudeau:"蒂博杜式", kayak:"皮划艇式", cambered:"弯杆", captains:"船长椅", clap:"击掌", clock:"时钟式", cocoons:"茧式", crab:"螃蟹式", curtsey:"屈膝礼式", cycle:"骑行", dead:"死虫式", bug:"虫式", deep:"深幅", diamond:"钻石式", bowling:"保龄球式", contralateral:"对侧", can:"罐式", breeding:"呼吸式", flyes:"飞鸟", kickbacks:"后踢", across:"交叉", femoral:"股部", pronated:"正握", supinated:"反握", peacher:"牧师凳", pronate:"旋前", scott:"斯科特式", rotate:"旋转", carry:"负重行走", stepbox:"踏步箱", above:"上方", supported:"支撑式", tate:"泰特式", waiter:"侍者式", dumbbells:"哑铃", dynamic:"动态", elevator:"电梯式", ground:"地面", pyramid:"金字塔式", ankles:"脚踝", legged:"单腿", diagonal:"对角", anti:"抗", gravity:"重力", farmers:"农夫", flag:"旗式", flutter:"交替摆腿", frankenstein:"弗兰肯斯坦式", reps:"重复", gironda:"吉隆达式", sternum:"胸骨", ham:"腘绳肌", gorilla:"大猩猩式", groin:"腹股沟", bends:"侧屈", reversed:"反向", keens:"膝部", hyght:"高位", impossible:"极限式", depth:"深度", intermediate:"中级", quad:"股四头肌", straps:"拉力带", wipers:"雨刷式", jackknife:"折刀式", janda:"扬达式", advanced:"高级", renegade:"叛徒式", position:"姿势", figure:"数字式", pirate:"海盗式", supper:"仰卧", seesaw:"跷跷板式", turkish:"土耳其式", z:"Z字", l:"L字", x:"X字"
});
Object.assign(words, {
  get:"起身", style:"式", out:"外展", kipping:"摆动式", korean:"韩式", lean:"倾斜", left:"左侧", hook:"勾拳", boxing:"拳击", gripper:"握力器", overhand:"正握", rotary:"旋转式", pad:"垫上", unilateral:"单侧", london:"伦敦式", catch:"接球", multiple:"多次", release:"释放", mixed:"混合握", hindu:"印度式", monster:"怪兽走", negative:"离心", crunches:"卷腹", otis:"奥蒂斯式", outside:"外侧", into:"进入", peroneals:"腓骨肌", cobra:"眼镜蛇式", tibialis:"胫骨肌", prisoner:"囚徒式", inside:"内侧", plus:"加强式", quarter:"四分之一程", quick:"快速", feet:"双脚", reclining:"后仰", big:"大幅", thrusts:"推髋", ring:"吊环", saw:"锯式", climb:"攀爬", equipment:"器械", runners:"跑者", scapular:"肩胛", scissor:"剪刀腿", angle:"角度", sequence:"组合", semi:"半程", short:"短程", stride:"跨步", outstretched:"伸展", platform:"平台", slide:"滑步", skater:"滑冰式", hops:"跳跃", ergometer:"功率车", skin:"皮肤", cat:"猫式", degrees:"度", closer:"更窄", angled:"角度式", sledge:"大锤", sprint:"冲刺", spell:"拼字式", caster:"脚轮式", sphinx:"斯芬克斯式", split:"分腿", stalder:"斯塔尔德式", staircase:"阶梯式", strap:"拉力带", star:"星式", outer:"外侧", abductor:"外展肌", superman:"超人式", fallout:"前倾伸展", swimmer:"游泳式", trap:"斜方肌", benches:"训练凳", twin:"双侧", handle:"手柄", upward:"向上", facing:"朝向", dog:"犬式", elliptical:"椭圆机", treadmill:"跑步机", stepmill:"登阶机", cossack:"哥萨克式", round:"圆背", svend:"斯文德式", wind:"风式", sprints:"冲刺", greatest:"大幅", rollerer:"滚轮"
});

function translateName(name) {
  let out = name.toLowerCase().replace(/_/g, " ");
  for (const [en, zh] of Object.entries(phrases).sort((a,b)=>b[0].length-a[0].length)) out = out.replace(new RegExp(`\\b${en.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}\\b`,"g"), ` ${zh} `);
  out = out.replace(/[a-z]+/g, (w) => words[w] ?? ({v:"V字",t:"T字",y:"Y字",jm:"JM式"}[w] || w.toUpperCase()));
  return out.replace(/\s+/g, " ").replace(/\s*([-–])\s*/g,"$1").replace(/\(\s*/g,"（").replace(/\s*\)/g,"）").trim();
}

const output = records.map((x) => ({
  id:x.id,
  nameZh:translateName(x.name),
  nameEn:x.name,
  category:categories[x.category] || x.category,
  equipment:equipment[x.equipment] || x.equipment,
  target:muscles[x.target] || x.target,
  muscleGroup:muscles[x.muscle_group] || x.muscle_group,
  secondaryMuscles:(x.secondary_muscles || []).map((v)=>muscles[v]||v),
  steps:x.instruction_steps?.zh || [x.instructions?.zh].filter(Boolean),
  image:`https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/${x.image}`,
  gif:`https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/${x.gif_url}`,
  attribution:x.attribution,
}));

const outPath = path.resolve("public/data/exercises-cn.json");
fs.mkdirSync(path.dirname(outPath), { recursive:true });
fs.writeFileSync(outPath, JSON.stringify(output));
const untranslated = output.filter((x)=>/[A-Z]{2,}/.test(x.nameZh)).length;
console.log(`已生成 ${output.length} 条动作，${(fs.statSync(outPath).size/1024).toFixed(1)} KB，含未映射缩写 ${untranslated} 条`);
